# Spring Boot配置文件

# 激活环境配置
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 8
        min-idle: 0
    timeout: 100
  cache:
    type: redis
    redis:
      time-to-live: 1d
      use-key-prefix: true
