server:
  port: 8085

spring:
  redis:
    host: 127.0.0.1
  http:
    encoding:
      charset: UTF-8
      force: true
  # Thymeleaf配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
  cache:
    type: redis

# 开启debug模式
debug: true

# 日志
logging:
  level:
    SpringBoot:
      Cache: debug
